### PR TITLE
Implement goodix5xx api

### PR DESCRIPTION
**Pull request by 0x00002a**
This implements a general API for (hopefully) all the goodixtls 5xxx (usb) devices. I'm making this a PR on the basis that I'd like feedback from other driver devs (I only know about 511) and get something that actually covers all the cases it needs too

## drivers to migrate
- [ ] [554b](https://github.com/TheWeirdDev/libfprint/tree/55b4-experimental) @TheWeirdDev
- [x] 511 @0x00002a

### CODE REVIEW

**Comment by mpi3d** [comment]
This has nothing to do with the pull request.

@rootd Hi, we are moving to a GitHub organisation. And we would like to transfer everything to it without losing pull request and all that stuff. Can you transfer `rootd/libfprint` to the `goodix-fp-linux-dev` org please?
Here is the procedure: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account.
Thanks

**Comment by rootd** [comment]
I just tried, but I got the message
"You don’t have the permission to create public repositories on goodix-fp-linux-dev " :-(

**Comment by mpi3d** [comment]
@rootd You need to accept the invitation from `goodix-fp-linux-dev` first to get write access.

**Comment by rootd** [comment]
@mpi3d whats your opinion on this PR?

**Comment by mpi3d** [comment]
> @mpi3d whats your opinion on this PR?

I think that we can merge it on [`goodix-fp-linux-dev:goodixtls`](https://github.com/goodix-fp-linux-dev/libfprint/tree/goodixtls). And push changes directly to this branch for now.

But we are far from a merge with libfprint. There are still a lot of things to implement.

Meanwhile we might provide prebuilt packages.

**Pull request merged**
